name: deploy website

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build
        shell: bash -l {0}
        run: |
          ${CONDA}/bin/conda init bash
          ${CONDA}/bin/conda activate base
          ${CONDA}/bin/conda install python pandoc
          pip install sphinx recommonmark nbsphinx ipython
          sphinx-build src build
      - name: Deploy
        if: github.ref == 'refs/heads/source'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
